/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paquete;

import javax.swing.JTextField;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.SwingUtilities;
import java.awt.Dimension;

/**
 *
 * @author pikip
 */
public class Questions extends javax.swing.JPanel {
    
    /**
     * Creates new form Preguntas
     */ 

    public Questions() {
        initComponents();
        
        //ESCALAR IMAGENES
        FondoBloque.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                String rutaImagen = "src/recursos/Cuadrado_Off.png";
                paquete.Utilidades.SetImageLabel(FondoBloque, rutaImagen);
            }
        });
        
        BtnMenos.setPreferredSize(new Dimension(17, 17)); // Fuerza un tamaño inicial (ajusta los valores según sea necesario)
        BtnMenos.setSize(50, 50); // Fuerza un tamaño inicial (ajusta los valores según sea necesario)

        SwingUtilities.invokeLater(() -> {
            String rutaImagen = "src/recursos/Menos_On.png";
            paquete.Utilidades.SetImageLabel(BtnMenos, rutaImagen);
        });
        
        
        
        FondoBloque.getParent().revalidate();
        FondoBloque.getParent().repaint();
        
        BtnMenos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                eliminarPregunta();
            }
        });
    }

    private void eliminarPregunta() {
        Main.instance.eliminarPregunta(this); // Llamar al método en Main
    }
        
        
    
    
    // Métodos para obtener los campos (getters)
    public JTextField getPregunta() {
        return Pregunta;
    }

    public JTextField getRCorrecta() {
        return RCorrecta;
    }

    public JTextField getRIncorrecta1() {
        return RIncorrecta1;
    }

    public JTextField getRIncorrecta2() {
        return RIncorrecta2;
    }

    public JTextField getRIncorrecta3() {
        return RIncorrecta3;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnMenos = new javax.swing.JLabel();
        TituloP1 = new javax.swing.JLabel();
        TituloRC = new javax.swing.JLabel();
        TituloRI = new javax.swing.JLabel();
        Pregunta = new javax.swing.JTextField();
        RCorrecta = new javax.swing.JTextField();
        RIncorrecta1 = new javax.swing.JTextField();
        RIncorrecta2 = new javax.swing.JTextField();
        RIncorrecta3 = new javax.swing.JTextField();
        FondoBloque = new javax.swing.JLabel();
        FondoPreguntas = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(430, 320));
        setMinimumSize(new java.awt.Dimension(430, 320));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(430, 320));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Menos_On.png"))); // NOI18N
        add(BtnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        TituloP1.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        TituloP1.setForeground(new java.awt.Color(247, 247, 247));
        TituloP1.setText("Pregunta");
        add(TituloP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 150, 20));

        TituloRC.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        TituloRC.setForeground(new java.awt.Color(247, 247, 247));
        TituloRC.setText("Respuesta correcta");
        add(TituloRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 20));

        TituloRI.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        TituloRI.setForeground(new java.awt.Color(247, 247, 247));
        TituloRI.setText("Respuestas incorrectas");
        add(TituloRI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 20));

        Pregunta.setBackground(new java.awt.Color(111, 114, 113));
        Pregunta.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        Pregunta.setForeground(new java.awt.Color(247, 247, 247));
        Pregunta.setMaximumSize(new java.awt.Dimension(350, 60));
        Pregunta.setMinimumSize(new java.awt.Dimension(350, 60));
        Pregunta.setPreferredSize(new java.awt.Dimension(350, 60));
        add(Pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        RCorrecta.setBackground(new java.awt.Color(111, 114, 113));
        RCorrecta.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        RCorrecta.setForeground(new java.awt.Color(247, 247, 247));
        RCorrecta.setMaximumSize(new java.awt.Dimension(350, 30));
        RCorrecta.setMinimumSize(new java.awt.Dimension(350, 30));
        RCorrecta.setPreferredSize(new java.awt.Dimension(350, 30));
        add(RCorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 350, -1));

        RIncorrecta1.setBackground(new java.awt.Color(111, 114, 113));
        RIncorrecta1.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        RIncorrecta1.setForeground(new java.awt.Color(247, 247, 247));
        RIncorrecta1.setMaximumSize(new java.awt.Dimension(350, 30));
        RIncorrecta1.setMinimumSize(new java.awt.Dimension(350, 30));
        RIncorrecta1.setPreferredSize(new java.awt.Dimension(350, 30));
        add(RIncorrecta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        RIncorrecta2.setBackground(new java.awt.Color(111, 114, 113));
        RIncorrecta2.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        RIncorrecta2.setForeground(new java.awt.Color(247, 247, 247));
        RIncorrecta2.setMaximumSize(new java.awt.Dimension(350, 30));
        RIncorrecta2.setMinimumSize(new java.awt.Dimension(350, 30));
        RIncorrecta2.setPreferredSize(new java.awt.Dimension(350, 30));
        add(RIncorrecta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        RIncorrecta3.setBackground(new java.awt.Color(111, 114, 113));
        RIncorrecta3.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        RIncorrecta3.setForeground(new java.awt.Color(247, 247, 247));
        RIncorrecta3.setMaximumSize(new java.awt.Dimension(350, 30));
        RIncorrecta3.setMinimumSize(new java.awt.Dimension(350, 30));
        RIncorrecta3.setPreferredSize(new java.awt.Dimension(350, 30));
        add(RIncorrecta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        FondoBloque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FondoBloque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Cuadrado_Off.png"))); // NOI18N
        FondoBloque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FondoBloque.setMaximumSize(new java.awt.Dimension(430, 320));
        FondoBloque.setMinimumSize(new java.awt.Dimension(430, 320));
        FondoBloque.setPreferredSize(new java.awt.Dimension(430, 320));
        add(FondoBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, 280));

        FondoPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo.png"))); // NOI18N
        FondoPreguntas.setText("jLabel1");
        FondoPreguntas.setMaximumSize(new java.awt.Dimension(430, 320));
        FondoPreguntas.setMinimumSize(new java.awt.Dimension(430, 320));
        FondoPreguntas.setPreferredSize(new java.awt.Dimension(430, 320));
        add(FondoPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnMenos;
    private javax.swing.JLabel FondoBloque;
    private javax.swing.JLabel FondoPreguntas;
    private javax.swing.JTextField Pregunta;
    private javax.swing.JTextField RCorrecta;
    private javax.swing.JTextField RIncorrecta1;
    private javax.swing.JTextField RIncorrecta2;
    private javax.swing.JTextField RIncorrecta3;
    private javax.swing.JLabel TituloP1;
    private javax.swing.JLabel TituloRC;
    private javax.swing.JLabel TituloRI;
    // End of variables declaration//GEN-END:variables
}
